<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default3.aspx.cs" Inherits="Default3" %>

<%@ Register Assembly="FredCK.FCKeditorV2" Namespace="FredCK.FCKeditorV2" TagPrefix="FCKeditorV2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        
    </div>
    testLogMsg<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <asp:Button ID="Button1" runat="server" Height="21px" onclick="Button1_Click" 
        Text="LogMsg" />
    <p>
    <asp:Button ID="Button4" runat="server" onclick="Button4_Click" 
        Text="getCalendar" />
    <asp:Button ID="Button5" runat="server" onclick="Button5_Click" Text="oneDay" />
    <asp:Button ID="Button2" runat="server" onclick="Button2_Click" Text="3Day" />
    <asp:Button ID="Button3" runat="server" onclick="Button3_Click" Text="未報名" />
    </p>
    <asp:GridView ID="GridView1" runat="server">
    </asp:GridView>
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:connStr %>" 
        DeleteCommand="DELETE FROM [ACSM_CALENDAR] WHERE [DAY] = @DAY AND [COMPANY_CODE] = @COMPANY_CODE" 
        InsertCommand="INSERT INTO [ACSM_CALENDAR] ([DAY], [COMPANY_CODE], [HOLIDAY_TYPE]) VALUES (@DAY, @COMPANY_CODE, @HOLIDAY_TYPE)" 
        SelectCommand="select  '' as DAY,COMPANY_CODE='',HOLIDAY_TYPE=''
union 
SELECT * FROM [ACSM_CALENDAR]" 
        UpdateCommand="UPDATE [ACSM_CALENDAR] SET [HOLIDAY_TYPE] = @HOLIDAY_TYPE WHERE [DAY] = @DAY AND [COMPANY_CODE] = @COMPANY_CODE">
        <DeleteParameters>
            <asp:Parameter Name="DAY" Type="DateTime" />
            <asp:Parameter Name="COMPANY_CODE" Type="String" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="HOLIDAY_TYPE" Type="String" />
            <asp:Parameter Name="DAY" Type="DateTime" />
            <asp:Parameter Name="COMPANY_CODE" Type="String" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="DAY" Type="DateTime" />
            <asp:Parameter Name="COMPANY_CODE" Type="String" />
            <asp:Parameter Name="HOLIDAY_TYPE" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
    <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    <asp:Button ID="Button6" runat="server" onclick="Button6_Click" Text="Insert" />
    <br />
    222<asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
    444<asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
    666<asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
    <br />
    <asp:GridView ID="GridView2" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
        DataKeyNames="DAY,COMPANY_CODE" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="DAY" HeaderText="DAY" ReadOnly="True" 
                SortExpression="DAY" />
            <asp:BoundField DataField="COMPANY_CODE" HeaderText="COMPANY_CODE" 
                ReadOnly="True" SortExpression="COMPANY_CODE" />
            <asp:BoundField DataField="HOLIDAY_TYPE" HeaderText="HOLIDAY_TYPE" 
                SortExpression="HOLIDAY_TYPE" />
        </Columns>
    </asp:GridView>
    <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
    <br />
    </form>
</body>
</html>
